[versions]
sloth = "0.3.2"
teamcode = "12.0.0-1.2.2"

[libraries]
sloth = { group = "dev.frozenmilk.sinister", name = "Sloth", version.ref = "sloth" }

[plugins]
sloth-load = { id = "dev.frozenmilk.sinister.sloth.load", version.ref = "sloth" }
teamcode = { id = "dev.frozenmilk.teamcode", version.ref = "teamcode" }
