[versions]
sloth = "0.2.4"
teamcode = "11.0.0-1.1.0"

[libraries]
sloth = { group = "dev.frozenmilk.sinister", name = "Sloth", version.ref = "sloth" }

[plugins]
sloth-load = { id = "dev.frozenmilk.sinister.sloth.load", version.ref = "sloth" }
teamcode = { id = "dev.frozenmilk.teamcode", version.ref = "teamcode" }
