[versions]
sdk = "11.1.0"
appcompat = "1.2.0"

[libraries]
inspection = { group = "org.firstinspires.ftc", name = "Inspection", version.ref = "sdk" }
blocks = { group = "org.firstinspires.ftc", name = "Blocks", version.ref = "sdk" }
robot-core = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "sdk" }
robot-server = { group = "org.firstinspires.ftc", name = "RobotServer", version.ref = "sdk" }
on-bot-java = { group = "org.firstinspires.ftc", name = "OnBotJava", version.ref = "sdk" }
hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "sdk" }
ftc-common = { group = "org.firstinspires.ftc", name = "FtcCommon", version.ref = "sdk" }
vision = { group = "org.firstinspires.ftc", name = "Vision", version.ref = "sdk" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[bundles]
sdk = ["inspection", "blocks", "robot-core", "robot-server", "on-bot-java", "hardware", "ftc-common", "vision", "appcompat"]
